language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    secure: "cIHcdnTxjEbjiLiF6YTkOebdyi+/Jq6YZo4joh/QOtUbP8ZwQ/l3VokuCDl4ZzW615RqU4Dz64auFHNxodW/n5IJLjJwEoJCuRCynqiT/LvvPjMPHpUJN99Iw4W9SqgpqqG+8WlBu63LB4CAzYaJx7gx6kUlQ1qN4I+0IMl13XsAa2nt9MAvRRp+j37/V2x3nkHTFoxp0/jBMaeocYle1V9QOyswggZCxxl2LLuOQHLR3203UGmnGpMSiwqtprt48zOtllHtDcH1eZG7f6J/zKQKPaxt+Dn6fOF0aPGFggihWn21ux2MD8yIJNZF7nv6SQ5P9Ha09jByr2OzAIAZYqlydxVmUrJdbdzR4HCQrjYpwS+sXlZW4E7rDmimrbcdCVfnqV7dZZgtsLR0z7eBFPDIwapgstRuarzRV6v3Mi2G7yjz4ejOG7u4S9ST5bO6jfcNSS0dsi78Hd/7tRE73UFFvhGvTvKVtXbY9Blad9fYUs+ASeTiJRERL13B+uCh4aIi4+TL778wZOKehLr+Ia4O3HWV15lb+pbH8ILiO/4kwJFC12cJG+LtN03Lsf5brEeMpIpbCH7QLRktxyHLH1ThOlruvHVb3HUyfoZ/HwXscB198o7hn1SSswcmyACiMRqWTw0gFu2eIqClC+tmzSR2MfqYdGFlfS0RlMS9bSo="

before_install:
  - travis_retry composer config --global github-oauth.github.com "$GITHUB_TOKEN"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - travis_retry composer require satooshi/php-coveralls --dev
  - travis_retry phpenv rehash

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpcs --standard=psr2 --extensions=php --ignore=*/vendor/* --exclude=PSR1.Files.SideEffects .
  - ./vendor/bin/phpunit --coverage-clover build/logs/coverage.clover

after_success:
  - travis_retry php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover
