<?php

/***
 * This script scans for all .po (human-readable) translation files which were
 * generated by the gettext_php_to_po.php script and creates corresponding
 * .mo (machine-readable) translation files for use by gettext().
 */

require_once __DIR__ . '/vendor/autoload.php';

use Gettext\Loader\PoLoader;
use Gettext\Generator\MoGenerator;

// Ensure that this script runs only from the command line
if (strlen($_SERVER['DOCUMENT_ROOT']) > 0) {
    exit;
}

// Run this script only from the script directory
if (__DIR__ != getcwd()) {
    echo 'Please run this script from the ' . __DIR__ . ' directory.' . "\n";
    exit;
}

// Run 'composer update' to pull in any library dependencies
$output = null;
if (
    (exec('composer -V', $output, $result_code) === false) ||
    ($result_code != 0)
) {
    echo "Unable to find 'composer' command.\n";
    echo "Please see https://getcomposer.org/doc/00-intro.md for installation.\n";
    exit;
}
exec('composer update');

// Scan for all .po files and generate machine-readable .mo files
foreach (glob('./{*,*/*,*/*/*,*/*/*/*,*/*/*/*/*,*/*/*/*/*/*}.po', GLOB_BRACE) as $file) {
    // Skip vendor libraries
    if (preg_match('%\./vendor/%', $file)) {
        continue;
    }

    echo "Processing $file\n";
    $loader = new PoLoader();
    $translations = $loader->loadFile($file);
    $moGenerator = new MoGenerator();
    $moFile = preg_replace('/\.po$/', '.mo', $file);
    $moGenerator->generateFile($translations, $moFile);
}

echo "Done!\n";
